<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-10">

<title>Reconstructing the Composite Metabolic Desirability Index after a triglyceride data correction – Codiet Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-86bc502edb2ebc763608229a1e047dca.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-b0ea6e064415e81711bfd68e230c8359.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Codiet Project</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">Metabolite Biomarkers &amp; Clinical Prediction For Metabolic Syndrome</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./cmdi_tg_correction_diagnostic.html">Sections</a></li><li class="breadcrumb-item"><a href="./cmdi_tg_correction_diagnostic.html">Index Reconstruction</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Sections</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cmdi_tg_correction_diagnostic.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Index Reconstruction</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#purpose-and-scope" id="toc-purpose-and-scope" class="nav-link active" data-scroll-target="#purpose-and-scope"><span class="header-section-number">1</span> Purpose and scope</a></li>
  <li><a href="#data-preparation-and-the-three-index-constructions" id="toc-data-preparation-and-the-three-index-constructions" class="nav-link" data-scroll-target="#data-preparation-and-the-three-index-constructions"><span class="header-section-number">2</span> Data preparation and the three index constructions</a>
  <ul class="collapse">
  <li><a href="#corrected-triglycerides-and-imputation" id="toc-corrected-triglycerides-and-imputation" class="nav-link" data-scroll-target="#corrected-triglycerides-and-imputation">Corrected triglycerides and imputation</a></li>
  <li><a href="#scale-of-the-triglyceride-change" id="toc-scale-of-the-triglyceride-change" class="nav-link" data-scroll-target="#scale-of-the-triglyceride-change">Scale of the triglyceride change</a></li>
  <li><a href="#v2-corrected-triglycerides-data-driven-bounds" id="toc-v2-corrected-triglycerides-data-driven-bounds" class="nav-link" data-scroll-target="#v2-corrected-triglycerides-data-driven-bounds">v2: corrected triglycerides, data-driven bounds</a></li>
  <li><a href="#v3-corrected-triglycerides-fixed-clinical-bounds" id="toc-v3-corrected-triglycerides-fixed-clinical-bounds" class="nav-link" data-scroll-target="#v3-corrected-triglycerides-fixed-clinical-bounds">v3: corrected triglycerides, fixed clinical bounds</a></li>
  </ul></li>
  <li><a href="#why-the-bounds-were-changed" id="toc-why-the-bounds-were-changed" class="nav-link" data-scroll-target="#why-the-bounds-were-changed"><span class="header-section-number">3</span> Why the bounds were changed</a>
  <ul class="collapse">
  <li><a href="#scores-that-depend-on-other-participants" id="toc-scores-that-depend-on-other-participants" class="nav-link" data-scroll-target="#scores-that-depend-on-other-participants">Scores that depend on other participants</a></li>
  <li><a href="#a-clinically-implausible-score" id="toc-a-clinically-implausible-score" class="nav-link" data-scroll-target="#a-clinically-implausible-score">A clinically implausible score</a></li>
  <li><a href="#selecting-the-bounds" id="toc-selecting-the-bounds" class="nav-link" data-scroll-target="#selecting-the-bounds">Selecting the bounds</a></li>
  <li><a href="#saturation-audit" id="toc-saturation-audit" class="nav-link" data-scroll-target="#saturation-audit">Saturation audit</a></li>
  </ul></li>
  <li><a href="#the-anchor-value" id="toc-the-anchor-value" class="nav-link" data-scroll-target="#the-anchor-value"><span class="header-section-number">4</span> The anchor value</a>
  <ul class="collapse">
  <li><a href="#the-specific-value-does-not-matter" id="toc-the-specific-value-does-not-matter" class="nav-link" data-scroll-target="#the-specific-value-does-not-matter">The specific value does not matter</a></li>
  </ul></li>
  <li><a href="#assembling-the-comparison" id="toc-assembling-the-comparison" class="nav-link" data-scroll-target="#assembling-the-comparison"><span class="header-section-number">5</span> Assembling the comparison</a></li>
  <li><a href="#distribution-of-the-three-indices" id="toc-distribution-of-the-three-indices" class="nav-link" data-scroll-target="#distribution-of-the-three-indices"><span class="header-section-number">6</span> Distribution of the three indices</a></li>
  <li><a href="#zero-collapse-audit" id="toc-zero-collapse-audit" class="nav-link" data-scroll-target="#zero-collapse-audit"><span class="header-section-number">7</span> Zero-collapse audit</a></li>
  <li><a href="#rank-stability" id="toc-rank-stability" class="nav-link" data-scroll-target="#rank-stability"><span class="header-section-number">8</span> Rank stability</a></li>
  <li><a href="#stratum-changes" id="toc-stratum-changes" class="nav-link" data-scroll-target="#stratum-changes"><span class="header-section-number">9</span> Stratum changes</a></li>
  <li><a href="#component-structure-and-relative-influence" id="toc-component-structure-and-relative-influence" class="nav-link" data-scroll-target="#component-structure-and-relative-influence"><span class="header-section-number">10</span> Component structure and relative influence</a>
  <ul class="collapse">
  <li><a href="#correlations-between-components" id="toc-correlations-between-components" class="nav-link" data-scroll-target="#correlations-between-components">Correlations between components</a></li>
  <li><a href="#relative-influence-of-each-component" id="toc-relative-influence-of-each-component" class="nav-link" data-scroll-target="#relative-influence-of-each-component">Relative influence of each component</a></li>
  </ul></li>
  <li><a href="#alternatives-considered" id="toc-alternatives-considered" class="nav-link" data-scroll-target="#alternatives-considered"><span class="header-section-number">11</span> Alternatives considered</a></li>
  <li><a href="#summary-and-remaining-checks" id="toc-summary-and-remaining-checks" class="nav-link" data-scroll-target="#summary-and-remaining-checks"><span class="header-section-number">12</span> Summary and remaining checks</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-body" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./cmdi_tg_correction_diagnostic.html">Sections</a></li><li class="breadcrumb-item"><a href="./cmdi_tg_correction_diagnostic.html">Index Reconstruction</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Reconstructing the Composite Metabolic Desirability Index after a triglyceride data correction</h1>
<p class="subtitle lead">Diagnostics for the index construction prior to refitting the prediction model</p>
</div>



<div class="quarto-title-meta column-body">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 10, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="purpose-and-scope" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Purpose and scope</h1>
<p>Triglyceride values were found to be inaccurate for a substantial share of observations in the biochemical panel. Because triglycerides are one of the four components from which the Composite Metabolic Desirability Index (CMDI) is built, the correction propagates into the outcome of the clinical prediction model rather than into a single predictor.</p>
<p>The prediction model is fitted with <code>bootPriorProc</code>, which takes approximately 6.2 hours to run. Repeating that run under several candidate constructions would be costly, so the purpose of this document is to settle the index construction first, using diagnostics that are less time consuming.</p>
<p>Three constructions are compared:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Label</th>
<th>Triglycerides</th>
<th>Desirability bounds</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>v1</strong></td>
<td>original</td>
<td>data-driven (<code>use_data = TRUE</code>)</td>
</tr>
<tr class="even">
<td><strong>v2</strong></td>
<td>corrected</td>
<td>data-driven (<code>use_data = TRUE</code>)</td>
</tr>
<tr class="odd">
<td><strong>v3</strong></td>
<td>corrected</td>
<td>fixed clinical bounds (<code>use_data = FALSE</code>)</td>
</tr>
</tbody>
</table>
<p>The three pairwise comparisons separate the two sources of change: v1 → v2 isolates the data correction, v2 → v3 isolates the parameterisation, and v1 → v3 gives the total that downstream reporting would have to absorb.</p>
<p>The prediction model is an ordinal regression one, which is rank-based and invariant to monotone transformations of the outcome. Changes in the <em>scale</em> or <em>spread</em> of the CMDI therefore have no effect on the fitted model; only changes in the <em>ordering</em> of participants do. Rank correlation is used throughout as the primary measure of impact for this reason.</p>
</section>
<section id="data-preparation-and-the-three-index-constructions" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Data preparation and the three index constructions</h1>
<section id="corrected-triglycerides-and-imputation" class="level2">
<h2 class="anchored" data-anchor-id="corrected-triglycerides-and-imputation">Corrected triglycerides and imputation</h2>
<p>Missing values are imputed with the same random-forest procedure used for the original analysis (<code>miceRanger</code>), and the multiply-imputed datasets are collapsed by taking the mean for numeric variables and the mode for character variables.</p>
</section>
<section id="scale-of-the-triglyceride-change" class="level2">
<h2 class="anchored" data-anchor-id="scale-of-the-triglyceride-change">Scale of the triglyceride change</h2>
<p>The correction is not marginal. Median triglycerides rise by half and the upper tail extends considerably further.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Statistic</th>
<th style="text-align: right;">Original</th>
<th style="text-align: right;">Corrected</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>n</td>
<td style="text-align: right;">299</td>
<td style="text-align: right;">296</td>
</tr>
<tr class="even">
<td>Mean</td>
<td style="text-align: right;">84.6</td>
<td style="text-align: right;">123.7</td>
</tr>
<tr class="odd">
<td>Median</td>
<td style="text-align: right;">70.0</td>
<td style="text-align: right;">105.0</td>
</tr>
<tr class="even">
<td>Gini mean difference</td>
<td style="text-align: right;">57.5</td>
<td style="text-align: right;">79.7</td>
</tr>
<tr class="odd">
<td>25th percentile</td>
<td style="text-align: right;">46.8</td>
<td style="text-align: right;">70.9</td>
</tr>
<tr class="even">
<td>75th percentile</td>
<td style="text-align: right;">107.0</td>
<td style="text-align: right;">141.7</td>
</tr>
<tr class="odd">
<td>95th percentile</td>
<td style="text-align: right;">180.2</td>
<td style="text-align: right;">235.0</td>
</tr>
<tr class="even">
<td>Maximum</td>
<td style="text-align: right;">590.1</td>
<td style="text-align: right;">1351.6</td>
</tr>
</tbody>
</table>
<p>The difference in row counts reflects three records with missing BMI, which the desirability functions exclude in either case; the analysis set is unaffected.</p>
</section>
<section id="v2-corrected-triglycerides-data-driven-bounds" class="level2">
<h2 class="anchored" data-anchor-id="v2-corrected-triglycerides-data-driven-bounds">v2: corrected triglycerides, data-driven bounds</h2>
<p>This is the construction as originally specified, with the triglyceride <code>scale</code> re-tuned so that the IDF threshold of 150 mg/dL continues to map to a desirability of 0.6 under the new data range.</p>
</section>
<section id="v3-corrected-triglycerides-fixed-clinical-bounds" class="level2">
<h2 class="anchored" data-anchor-id="v3-corrected-triglycerides-fixed-clinical-bounds">v3: corrected triglycerides, fixed clinical bounds</h2>
<p>The bounds are stated explicitly and the <code>scale</code> for each component is solved so that the clinical anchor is preserved exactly. Solving rather than hard-coding means a change to any bound cannot silently break the anchoring.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Component</th>
<th>Kind</th>
<th style="text-align: right;">low</th>
<th style="text-align: right;">high</th>
<th style="text-align: right;">anchor</th>
<th style="text-align: right;">target</th>
<th style="text-align: right;">scale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>BMI</td>
<td><code>d_max</code></td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.553</td>
</tr>
<tr class="even">
<td>TRIG</td>
<td><code>d_max</code></td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">150</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.349</td>
</tr>
<tr class="odd">
<td>HDL</td>
<td><code>d_min</code></td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">130</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">2.010</td>
</tr>
<tr class="even">
<td>GLU</td>
<td><code>d_max</code></td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">500</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.340</td>
</tr>
</tbody>
</table>
<p>A small floor is applied to each component before aggregation. Under a geometric mean a single component at zero forces the whole index to zero, so the floor prevents one extreme value from erasing the information in the other three. With the bounds above no observation reaches the floor, so it acts as insurance rather than doing real work.</p>
</section>
</section>
<section id="why-the-bounds-were-changed" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Why the bounds were changed</h1>
<p>The move from data-driven to fixed bounds was not part of the original plan. It was prompted by two observations that emerged while diagnosing the correction.</p>
<section id="scores-that-depend-on-other-participants" class="level2">
<h2 class="anchored" data-anchor-id="scores-that-depend-on-other-participants">Scores that depend on other participants</h2>
<p>With <code>use_data = TRUE</code> the desirability bounds are taken from the observed range, so the participant holding the sample minimum receives a desirability of exactly zero on that component. Because the index is a geometric mean, that zero propagates to the whole index.</p>
<p>The clearest example is ID 132 at timepoint 3. Their triglyceride value is 35 mg/dL in both the original and corrected datasets, it did not change. Their CMDI nonetheless fell from 43.5 to 0, because the sample minimum moved from 15.47 up to 35, making them the new floor-holder.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>ID</th>
<th>Timepoint</th>
<th style="text-align: right;">TRIG (v1)</th>
<th style="text-align: right;">TRIG (v2)</th>
<th style="text-align: right;">CMDI v1</th>
<th style="text-align: right;">CMDI v2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>132</td>
<td>3</td>
<td style="text-align: right;">35.0</td>
<td style="text-align: right;">35.0</td>
<td style="text-align: right;">43.5</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td>207</td>
<td>1</td>
<td style="text-align: right;">15.5</td>
<td style="text-align: right;">35.4</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">19.6</td>
</tr>
</tbody>
</table>
<p>An index in which one participant’s score changes because a different participant’s data changed is difficult to defend as an individual-level quantity, and it is incompatible with applying the index to an external cohort.</p>
</section>
<section id="a-clinically-implausible-score" class="level2">
<h2 class="anchored" data-anchor-id="a-clinically-implausible-score">A clinically implausible score</h2>
<p>ID 132 at timepoint 3 has BMI 31.1, HDL 50, glucose 96 and triglycerides 35. A CMDI of zero places this participant at the most metabolically desirable end of the scale, which is not a reasonable description of someone in the obese BMI range. The zero is an artefact of the floor mechanism rather than a summary of their metabolic state.</p>
</section>
<section id="selecting-the-bounds" class="level2">
<h2 class="anchored" data-anchor-id="selecting-the-bounds">Selecting the bounds</h2>
<p>Three criteria were used, in order:</p>
<ol type="1">
<li>Clinical defensibility: Bounds anchored to published thresholds and chosen a priori rather than from the observed data.</li>
<li>Coverage: Wide enough that saturation is rare, verified empirically. This matters because a saturated value carries no information: every observation beyond a bound receives an identical desirability.</li>
<li>Portability: Fixed, so that the index can be computed identically in an external cohort.</li>
</ol>
<p>The bounds were widened iteratively. An initial set (BMI 16–55, TG 20–500, HDL 20–110, glucose 55–250) produced 23 observations at the floor, driven by HDL ≥ 80 and glucose ≤ 70 — both common values rather than clinical extremes. The final set places each bound beyond the plausible clinical range: severe underweight through super-obesity for BMI, values below any plausible fasting measurement through the threshold for pancreatitis risk for triglycerides, severe hypoalphalipoproteinaemia through exceptional hyperalphalipoproteinaemia for HDL, and clinical hypoglycaemia through marked hyperglycaemia for glucose.</p>
</section>
<section id="saturation-audit" class="level2">
<h2 class="anchored" data-anchor-id="saturation-audit">Saturation audit</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">BMI_lo</th>
<th style="text-align: right;">BMI_hi</th>
<th style="text-align: right;">TRIG_lo</th>
<th style="text-align: right;">TRIG_hi</th>
<th style="text-align: right;">HDL_lo</th>
<th style="text-align: right;">HDL_hi</th>
<th style="text-align: right;">GLU_lo</th>
<th style="text-align: right;">GLU_hi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p>No observation reaches a lower bound, so the zero-collapse mechanism cannot operate. One observation sit at or above the triglyceride ceiling of 1000 mg/dL. This is acceptable: values in that range fall into a clinically homogeneous category in which management does not differentiate further, so collapsing them is a reasonable simplification rather than a loss.</p>
</section>
</section>
<section id="the-anchor-value" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> The anchor value</h1>
<p>Each component’s <code>target</code> states the desirability assigned to a participant sitting exactly at the IDF threshold. The original specification used 0.5 where the IDF states a criterion with a strict inequality and 0.6 where it uses a non-strict inequality, on the reasoning that a participant at the threshold has already met the criterion in the latter case.</p>
<p>The direction of that adjustment follows from the definition, but the magnitude does not. The distinction between <code>&gt;150</code> and <code>≥150</code> concerns a single point on a continuous scale, and encoding it as a 0.1 shift in desirability, which propagates to a 36% change in the scale parameter, gives it more weight than it can carry. Two of the four anchors are also not clean IDF thresholds: the HDL anchor of 45 mg/dL is a sex-neutral compromise between the 40 mg/dL and 50 mg/dL criteria, and BMI &gt; 30 is the IDF’s surrogate provision for when waist circumference is unavailable rather than the primary criterion.</p>
<p>A single anchor is used for all four components instead. The justification is that the IDF assigns equal status to each criterion (each contributes one qualifying condition, none counts for more than another) so mapping all four thresholds to the same desirability preserves that equivalence.</p>
<section id="the-specific-value-does-not-matter" class="level2">
<h2 class="anchored" data-anchor-id="the-specific-value-does-not-matter">The specific value does not matter</h2>
<p>With a uniform target <span class="math inline">\(c\)</span> across components, the scale for component <span class="math inline">\(i\)</span> is <span class="math inline">\(s_i = \log c / \log f_{a,i}\)</span> where <span class="math inline">\(f_{a,i}\)</span> is the anchor’s fractional position within the bounds. Then</p>
<p><span class="math display">\[\log d_i = s_i \log f_i = \log c \cdot \frac{\log f_i}{\log f_{a,i}}\]</span></p>
<p>and the log of the aggregated index is</p>
<p><span class="math display">\[\log \text{CMDI} = \frac{1}{4}\sum_i \log d_i = \log c \cdot K, \qquad
K = \frac{1}{4}\sum_i \frac{\log f_i}{\log f_{a,i}}\]</span></p>
<p><span class="math inline">\(K\)</span> does not involve <span class="math inline">\(c\)</span>, so <span class="math inline">\(\text{CMDI} = c^{K}\)</span> is a strictly monotone function of the same underlying quantity for any <span class="math inline">\(c \in (0,1)\)</span>. Participant ordering is therefore identical for every uniform anchor, and because all component influences scale by <span class="math inline">\(|\log c|\)</span> together, the relative weighting is unchanged as well.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">c_target</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">spearman</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">16.47</td>
<td style="text-align: right;">6.49</td>
<td style="text-align: right;">39.42</td>
<td style="text-align: right;">0.999972</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">25.94</td>
<td style="text-align: right;">10.95</td>
<td style="text-align: right;">49.84</td>
<td style="text-align: right;">1.000000</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">35.81</td>
<td style="text-align: right;">18.58</td>
<td style="text-align: right;">58.86</td>
<td style="text-align: right;">1.000000</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">45.98</td>
<td style="text-align: right;">27.99</td>
<td style="text-align: right;">66.97</td>
<td style="text-align: right;">1.000000</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.6</td>
<td style="text-align: right;">56.41</td>
<td style="text-align: right;">39.13</td>
<td style="text-align: right;">74.42</td>
<td style="text-align: right;">1.000000</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.7</td>
<td style="text-align: right;">67.05</td>
<td style="text-align: right;">51.94</td>
<td style="text-align: right;">81.36</td>
<td style="text-align: right;">1.000000</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">77.87</td>
<td style="text-align: right;">66.37</td>
<td style="text-align: right;">87.89</td>
<td style="text-align: right;">1.000000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The rank correlation against the reference is exactly 1 for every value tested, confirming that the choice is a labelling decision. A value of 0.5 is used as the midpoint of the scale, and the <code>Methods</code> section of the paper can state plainly that the specific value is inconsequential.</p>
</section>
</section>
<section id="assembling-the-comparison" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Assembling the comparison</h1>
<p>The high-risk cut-point is the median of each index. Because the cut is defined this way, each version splits the cohort in half by construction, so changes in stratum membership reflect rank movement rather than a shift in the overall distribution.</p>
</section>
<section id="distribution-of-the-three-indices" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Distribution of the three indices</h1>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 37%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">version</th>
<th style="text-align: right;">cut</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">gmd</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">n_zero</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">v1 original</td>
<td style="text-align: right;">44.29</td>
<td style="text-align: right;">44.29</td>
<td style="text-align: right;">43.00</td>
<td style="text-align: right;">14.27</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">77.73</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">v2 TG-corrected</td>
<td style="text-align: right;">46.21</td>
<td style="text-align: right;">46.21</td>
<td style="text-align: right;">45.11</td>
<td style="text-align: right;">14.36</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">78.88</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">v3 TG-corr + fixed bounds</td>
<td style="text-align: right;">45.83</td>
<td style="text-align: right;">45.83</td>
<td style="text-align: right;">45.60</td>
<td style="text-align: right;">7.06</td>
<td style="text-align: right;">27.99</td>
<td style="text-align: right;">66.97</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Descriptive statistics for the final construction over the full set of 296 scored observations:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Statistic</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>n</td>
<td style="text-align: right;">296</td>
</tr>
<tr class="even">
<td>Distinct values</td>
<td style="text-align: right;">296</td>
</tr>
<tr class="odd">
<td>Mean</td>
<td style="text-align: right;">45.68</td>
</tr>
<tr class="even">
<td>Median</td>
<td style="text-align: right;">45.98</td>
</tr>
<tr class="odd">
<td>Gini mean difference</td>
<td style="text-align: right;">6.99</td>
</tr>
<tr class="even">
<td>5th percentile</td>
<td style="text-align: right;">34.48</td>
</tr>
<tr class="odd">
<td>25th percentile</td>
<td style="text-align: right;">41.54</td>
</tr>
<tr class="even">
<td>75th percentile</td>
<td style="text-align: right;">50.25</td>
</tr>
<tr class="odd">
<td>95th percentile</td>
<td style="text-align: right;">54.34</td>
</tr>
<tr class="even">
<td>Minimum</td>
<td style="text-align: right;">27.99</td>
</tr>
<tr class="odd">
<td>Maximum</td>
<td style="text-align: right;">66.97</td>
</tr>
</tbody>
</table>
<p>Two features are worth commenting on.</p>
<p>The index is more compressed than under data-driven bounds, with 90% of participants between roughly 34 and 54. This is expected: the bounds now represent clinically extreme values, and a score near 90 would require a participant to sit near the pathological extreme of all four components at once. Under a geometric mean, four moderate desirabilities produce a moderate composite. Since <code>ordinal regression</code> is invariant to monotone transformation, the compression has no effect on the model.</p>
<p>The maximum is also lower than under data-driven bounds. This is arguably more honest: <code>use_data = TRUE</code> places the worst participant near the top of the scale by construction, which gives a misleading impression that the cohort spans the full range of metabolic risk. Fixed anchors make it visible that it does not, which is consistent with the limitation already noted in the manuscript.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-distributions" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-distributions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="cmdi_tg_correction_diagnostic_files/figure-html/fig-distributions-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-distributions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: CMDI distributions under the three constructions, with the published cut-point and the re-derived cut-point marked.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The histogram of the adopted construction is unimodal with a slightly longer lower tail and no pile-up at either boundary. Apparent shoulders in the kernel density estimate do not persist across bin widths and are attributable to smoothing rather than structure.</p>
</section>
<section id="zero-collapse-audit" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Zero-collapse audit</h1>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Version</th>
<th style="text-align: right;">Observations with a zero component</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>v1 original</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td>v2 TG-corrected</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td>v3 fixed bounds</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td>v3 before the floor</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p>The four observations that collapsed to zero under data-driven bounds receive plausible scores under fixed bounds:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">ID</th>
<th style="text-align: right;">Timepoint</th>
<th style="text-align: right;">ms_score_v1</th>
<th style="text-align: right;">ms_score_v2</th>
<th style="text-align: right;">ms_score_v3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">113</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">28.20</td>
</tr>
<tr class="even">
<td style="text-align: right;">113</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">27.99</td>
</tr>
<tr class="odd">
<td style="text-align: right;">132</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">39.48</td>
<td style="text-align: right;">40.17</td>
<td style="text-align: right;">41.07</td>
</tr>
<tr class="even">
<td style="text-align: right;">132</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">43.52</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">41.20</td>
</tr>
<tr class="odd">
<td style="text-align: right;">207</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">19.62</td>
<td style="text-align: right;">35.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">207</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">43.64</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="rank-stability" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Rank stability</h1>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 31%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">comparison</th>
<th style="text-align: right;">spearman</th>
<th style="text-align: right;">kendall</th>
<th style="text-align: right;">pearson</th>
<th style="text-align: right;">med_abs_rank_shift</th>
<th style="text-align: right;">pct_moving_gt10pct</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">v1 -&gt; v2 (data correction)</td>
<td style="text-align: right;">0.9663</td>
<td style="text-align: right;">0.8595</td>
<td style="text-align: right;">0.9531</td>
<td style="text-align: right;">12.5</td>
<td style="text-align: right;">10.7407</td>
</tr>
<tr class="even">
<td style="text-align: left;">v2 -&gt; v3 (parameterisation)</td>
<td style="text-align: right;">0.9472</td>
<td style="text-align: right;">0.8052</td>
<td style="text-align: right;">0.9204</td>
<td style="text-align: right;">14.5</td>
<td style="text-align: right;">22.2222</td>
</tr>
<tr class="odd">
<td style="text-align: left;">v1 -&gt; v3 (total)</td>
<td style="text-align: right;">0.9193</td>
<td style="text-align: right;">0.7584</td>
<td style="text-align: right;">0.9105</td>
<td style="text-align: right;">18.0</td>
<td style="text-align: right;">34.4444</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-scatter" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="cmdi_tg_correction_diagnostic_files/figure-html/fig-scatter-1.png" class="img-fluid figure-img" width="1056">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Participant-level comparison of the three constructions.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Ordering is well preserved across all three comparisons, which is the quantity that determines whether the refitted model will resemble the published one. The correction and the reparameterisation each contribute a comparable amount of movement, and neither dominates.</p>
</section>
<section id="stratum-changes" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Stratum changes</h1>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">comparison</th>
<th style="text-align: right;">n_changed</th>
<th style="text-align: right;">pct</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">v1 -&gt; v2</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">6.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">v2 -&gt; v3</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">11.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">v1 -&gt; v3</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">11.9</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>v1 -&gt; v3</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">high</th>
<th style="text-align: right;">low</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">high</td>
<td style="text-align: right;">119</td>
<td style="text-align: right;">16</td>
</tr>
<tr class="even">
<td style="text-align: left;">low</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">119</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Observations closest to the cut-point are those most likely to move again on refitting, and are listed below for reference.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">ID</th>
<th style="text-align: right;">Timepoint</th>
<th style="text-align: right;">ms_score_v1</th>
<th style="text-align: right;">ms_score_v3</th>
<th style="text-align: right;">dist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">32</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">46.114</td>
<td style="text-align: right;">45.808</td>
<td style="text-align: right;">0.019</td>
</tr>
<tr class="even">
<td style="text-align: right;">135</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">48.328</td>
<td style="text-align: right;">45.846</td>
<td style="text-align: right;">0.019</td>
</tr>
<tr class="odd">
<td style="text-align: right;">35</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">45.465</td>
<td style="text-align: right;">45.919</td>
<td style="text-align: right;">0.092</td>
</tr>
<tr class="even">
<td style="text-align: right;">47</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">40.945</td>
<td style="text-align: right;">45.921</td>
<td style="text-align: right;">0.094</td>
</tr>
<tr class="odd">
<td style="text-align: right;">143</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">45.078</td>
<td style="text-align: right;">46.014</td>
<td style="text-align: right;">0.186</td>
</tr>
<tr class="even">
<td style="text-align: right;">51</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">45.267</td>
<td style="text-align: right;">45.525</td>
<td style="text-align: right;">0.303</td>
</tr>
<tr class="odd">
<td style="text-align: right;">51</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">45.267</td>
<td style="text-align: right;">45.525</td>
<td style="text-align: right;">0.303</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">46.851</td>
<td style="text-align: right;">45.193</td>
<td style="text-align: right;">0.635</td>
</tr>
<tr class="odd">
<td style="text-align: right;">135</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">46.987</td>
<td style="text-align: right;">45.187</td>
<td style="text-align: right;">0.640</td>
</tr>
<tr class="even">
<td style="text-align: right;">17</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">47.502</td>
<td style="text-align: right;">45.180</td>
<td style="text-align: right;">0.648</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="component-structure-and-relative-influence" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Component structure and relative influence</h1>
<section id="correlations-between-components" class="level2">
<h2 class="anchored" data-anchor-id="correlations-between-components">Correlations between components</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Spearman correlations between component desirabilities</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">d_BMI</th>
<th style="text-align: right;">d_TRIG</th>
<th style="text-align: right;">d_HDL</th>
<th style="text-align: right;">d_GLU</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">d_BMI</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.198</td>
<td style="text-align: right;">0.149</td>
<td style="text-align: right;">0.118</td>
</tr>
<tr class="even">
<td style="text-align: left;">d_TRIG</td>
<td style="text-align: right;">0.198</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.327</td>
<td style="text-align: right;">-0.045</td>
</tr>
<tr class="odd">
<td style="text-align: left;">d_HDL</td>
<td style="text-align: right;">0.149</td>
<td style="text-align: right;">0.327</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">-0.004</td>
</tr>
<tr class="even">
<td style="text-align: left;">d_GLU</td>
<td style="text-align: right;">0.118</td>
<td style="text-align: right;">-0.045</td>
<td style="text-align: right;">-0.004</td>
<td style="text-align: right;">1.000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The components are only weakly associated. The strongest relationship, between triglycerides and HDL, is consistent with atherogenic dyslipidaemia. Glucose is close to independent of both lipid components, which is less expected given that insulin resistance would predict some association along the same axis.</p>
<p>Two implications can be noted. First, it explains why the index is sensitive to how the components are weighted: with near-orthogonal components there is little shared variance to stabilise the aggregate. Second, it is worth noting that the CMDI is a multi-response desirability aggregation rather than a latent-variable measurement model. The Derringer–Suich framework makes no assumption that the components load on a common factor; it aggregates desirability, which is a statement about what is clinically preferable rather than a claim about dimensionality. This distinguishes the approach from factor-analytic severity scores, which do assume a single underlying factor.</p>
</section>
<section id="relative-influence-of-each-component" class="level2">
<h2 class="anchored" data-anchor-id="relative-influence-of-each-component">Relative influence of each component</h2>
<p>Under a geometric mean, each component’s contribution to variation in the composite is governed by the spread of its log-desirability. Since <span class="math inline">\(\log d_i = s_i \log f_i\)</span>, influence is proportional to the scale parameter.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Component</th>
<th style="text-align: right;">Share of composite variation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>BMI</td>
<td style="text-align: right;">18.8%</td>
</tr>
<tr class="even">
<td>TRIG</td>
<td style="text-align: right;">25.6%</td>
</tr>
<tr class="odd">
<td>HDL</td>
<td style="text-align: right;">46.7%</td>
</tr>
<tr class="even">
<td>GLU</td>
<td style="text-align: right;">8.9%</td>
</tr>
</tbody>
</table>
<p>The contributions are uneven, with HDL carrying close to half the variation and glucose under a tenth. This is a consequence of where each anchor falls within its bounds rather than a deliberate weighting: HDL is the only component whose anchor sits in the upper part of its range, which produces a convex transform that expands differences, while the other three have concave transforms that compress them. For a <code>d_min</code> component, widening the upper bound pushes the anchor fraction toward 1 and inflates the scale parameter sharply, so the widening adopted for portability necessarily increased HDL’s influence.</p>
<p>This is reported as a property of the construction rather than corrected, for reasons set out in the next section.</p>
</section>
</section>
<section id="alternatives-considered" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Alternatives considered</h1>
<p>Several alternative parameterisations were tested and set aside. Each is recorded here because the reasons for rejection are part of the justification for the adopted construction.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Alternative</th>
<th style="text-align: right;">Rank correlation with adopted</th>
<th>Reason for rejection</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Data-driven bounds (<code>use_data = TRUE</code>)</td>
<td style="text-align: right;">—</td>
<td>Scores depend on other participants’ data; four observations collapse to zero</td>
</tr>
<tr class="even">
<td>Mixed anchors (0.5 / 0.6 by inequality type)</td>
<td style="text-align: right;">0.989</td>
<td>Direction defensible, magnitude disproportionate to a single-point distinction</td>
</tr>
<tr class="odd">
<td>Targets solved to equalise contributions</td>
<td style="text-align: right;">0.911</td>
<td>Derived from the sample’s own variances, and the IDF thresholds map to desirabilities spanning 0.24–0.76 with no clinical meaning</td>
</tr>
<tr class="even">
<td>Linear transform (<code>target</code> = anchor fraction)</td>
<td style="text-align: right;">—</td>
<td>Abandons the anchoring entirely; triglycerides then dominate at roughly 47%</td>
</tr>
<tr class="odd">
<td>Narrow symmetric bounds</td>
<td style="text-align: right;">0.982</td>
<td>43 observations (14.5%) saturate at the HDL ceiling, reintroducing the zero-collapse problem</td>
</tr>
</tbody>
</table>
<p>Note on two of these:</p>
<p><strong>Equalising the component contributions</strong> is achievable by solving for the target that gives each component the required scale. It was rejected on two grounds. The solution depends on the spread of each component in this particular sample, so it reintroduces the sample-dependence that motivated the move away from data-driven bounds, simply relocated from the bounds to the targets. It also empties the target of clinical meaning: a participant at the glucose threshold would be scored as less metabolically undesirable than one at the HDL threshold, by a factor of three, with no rationale. There is also a tension with the argument made in the manuscript’s introduction, which criticises binary definitions for treating criteria as equivalent despite heterogeneous risk implications; equal weighting by construction does the same thing.</p>
<p><strong>Narrow symmetric bounds</strong> are attractive because bounds symmetric about the anchor give a scale of exactly 1, producing a linear transform with the threshold at the midpoint. The rank correlation with the adopted construction was 0.982, which initially looked acceptable. The saturation audit showed why it was not: 43 observations sat at or above an HDL ceiling of 70 mg/dL, a value that is common rather than extreme. The high rank correlation persisted because the clamping is directionally correct — high HDL is protective and those participants belong at the low-risk end — but their HDL information is lost. This is a useful reminder that rank correlation alone does not detect degraded measurement.</p>
</section>
<section id="summary-and-remaining-checks" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> Summary and remaining checks</h1>
<p>The adopted construction uses corrected triglycerides, fixed clinical bounds, a uniform anchor of 0.5, and a small floor applied before aggregation. On the evidence assembled here:</p>
<ul>
<li>No component can reach zero, so the geometric-mean collapse that produced implausible scores under data-driven bounds cannot occur.</li>
<li>Saturation is limited to one observation at the triglyceride ceiling, in a range where clinical management does not differentiate.</li>
<li>Participant ordering is well preserved relative to the published index, so the refitted model is expected to resemble the published one in structure, with movement concentrated among predictors near the selection threshold.</li>
<li>The index no longer depends on which participants happen to be in the sample, which is a prerequisite for the external validation described in the manuscript.</li>
<li>Component contributions are uneven and this is disclosed rather than adjusted, since every attempt to balance them cost more in interpretability or portability than it gained.</li>
</ul>
<p>A check before refitting:</p>
<p>The near-zero correlation between glucose and the lipid components is not what insulin-resistance pathophysiology would predict, particularly since the triglyceride–HDL association is present. Given that an error has already been found in this panel, it is worth confirming that fasting status was standardised and recorded, and that glucose was assayed from the same draw as the lipids. Inconsistent fasting would decorrelate glucose while leaving the lipid relationships intact, which matches the observed pattern.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>CODIET · WP2</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Built with Quarto</p>
</div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>